from stack import Stack

aStack = Stack()
aStack.print()
aStack.push(10)
aStack.print()
aStack.push(100)
aStack.print()
aStack.pop()
aStack.print()
aStack.push(99)
aStack.print()
aStack.push(88)
aStack.print()
aStack.invert()
aStack.print()